version: "3"
services:
  backend:
    build: ./backend/
    container_name: game_backend
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: game_database
    environment:
      SA_PASSWORD: "Password2020"
      ACCEPT_EULA: "Y"
    ports:
      - "3456:1433"
